### PR TITLE
Update index.d.ts to match most recent package version

### LINKED ISSUE #3: Missing TypeScript types in latest version
This library was recently updated to be compatible with the latest versions of lowdb. As lowdb's API has changed, I believe the work that @KeithBrown39423 did to add the type declaration is no longer compatible in this version (at least, I was getting TypeScript errors).

I'm not experienced enough with TypeScript to update the declaration file. In the meantime, I removed the now incorrect `index.d.ts` and the `types` property in `package.json`.

### PR DESCRIPTION
**Pull request by KeithBrown39423**
Fix #3

### CODE REVIEW

**Comment by travishorn** [comment]
This could totally be some misconfiguration on my end, but TypeScript gives me the following errors in `index.d.ts`.

Ln 16, Col 10:

> Property 'touch' in type 'LowdbStore' is not assignable to the same property in base type 'Store'.
>   Type '(sid: string, session: SessionData, cb: (err: any) => any) => void' is not assignable to type '(sid: string, session: SessionData, callback?: (() => void) | undefined) => void'.
>     Types of parameters 'cb' and 'callback' are incompatible.
>       Type '(() => void) | undefined' is not assignable to type '(err: any) => any'.
>         Type 'undefined' is not assignable to type '(err: any) => any'.

Ln 24, Col 5:

> Exports and export assignments are not permitted in module augmentations.

**Comment by KeithBrown39423** [comment]
I don't know why you are getting the error on line 24, I can't seem to reproduce that one

**Comment by KeithBrown39423** [comment]
I managed to reproduce the issue, and it should now no longer have that issue.

**Comment by KeithBrown39423** [comment]
Let me know if it has any issues

**Comment by travishorn** [comment]
Thanks! You're the man.

**Pull request merged**
